Fix t.repos race.
Symptom was a failure like this:

================= repos test (1/1) ============================
Create initial repository ...................................failed in line 29
Files ../longline and /build/.regression georgn/sandbox/.bk/repos/ff/rex.bitkeeper.com/path.log differ
--- ../longline	2016-05-26 16:09:39 -04:00
+++ /build/.regression georgn/sandbox/.bk/repos/ff/rex.bitkeeper.com/path.log	2016-05-26 16:09:39 -04:00
@@ -1,2 +1,3 @@
 /build/.regression georgn/sandbox/commercial|1464293378|1464293378|57475802zsIolfC-evoK-SbSJRA96Q|one|two|three
 /build/.regression georgn/sandbox/project|1464293379|1464293379|57475803BgZAlXVYBdl0NUOgi9TuOw
+/build/.regression georgn/sandbox/commercial|1464293379|1464293378|57475802zsIolfC-evoK-SbSJRA96Q
ERROR: Test repos failed with error 1

Or:

================= repos test (1/1) ============================
Create initial repository ...................................OK
Check that check updates cache ..............................OK
Check that long lines stay long, short lines grow back ......failed in line 55
Files WANT and GOT differ
--- WANT	2016-05-26 16:13:11 -04:00
+++ GOT	2016-05-26 16:13:11 -04:00
@@ -1,3 +1,2 @@
-/build/.regression georgn/sandbox/commercial|1464293590|1464293590|574758d63nsBIsP0ozOIG67MeNFwbA|one|two|three
 /build/.regression georgn/sandbox/commercial|1464293591|1464293590|574758d63nsBIsP0ozOIG67MeNFwbA|one|two|three
 /build/.regression georgn/sandbox/project|1464293591|1464293591|574758d79f2_7N3Xm2--fYV8uzkg4A
ERROR: Test repos failed with error 1

bk: 57484319uTJovlwAgKXRoUiaB9ctIg