Make build script default to -j4.
Exception: punt on Windows.
When we upgrade to a more recent msys/mingw we can try again.

bk: 510abdcdSPdI9JRUht2MtU2rvTerUg