Wayne wanted a testcase for the create-create conflict.
================= fast-import test (1/1) ======================
Create-create conflict.......................................

--- GIT TREE ---
*   a2524b0 merge of merges
|\  
| *   981cdf0 merge 1
| |\  
* | \   4403843 merge 2
|\ \ \  
| |/ /  
| | /   
| |/    
|/|     
| * 4366ae6 create-create (side 2)
* | be4a291 create-create (side 1)
|/  
* 66b9ac4 add afile
---
BitKeeper/deleted/24/SCCS/s.create-create~d4762235b21bfcf1: unmerged leaf 1.1.1.1
BitKeeper/deleted/24/SCCS/s.create-create~d4762235b21bfcf1: unmerged leaf 1.2
failed in line 68
ERROR: Test fast-import failed with error 1

bk: 574e0a80BAH92UGzJ23gTRwHsQ7b6g