macosx: fix autoconf breakage caused by recent clang
Recent clang reports error on implicitly declaring library function:
```
conftest.c:80:6: error: implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))' [-Werror,-Wimplicit-function-declaration]
```